/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicholas
 */
public class ConsultaPreferencia extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPreferencia
     */
    public ConsultaPreferencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarTf = new javax.swing.JButton();
        fecharTf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        registroFuncionarioTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inforamacoesTa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consultarTf.setText("Consultar");
        consultarTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarTfActionPerformed(evt);
            }
        });

        fecharTf.setText("Fechar");
        fecharTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharTfActionPerformed(evt);
            }
        });

        jLabel1.setText("Registro do funcionário:");

        registroFuncionarioTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroFuncionarioTfActionPerformed(evt);
            }
        });

        inforamacoesTa.setColumns(20);
        inforamacoesTa.setRows(5);
        jScrollPane1.setViewportView(inforamacoesTa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registroFuncionarioTf, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(consultarTf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecharTf)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharTf)
                    .addComponent(consultarTf)
                    .addComponent(jLabel1)
                    .addComponent(registroFuncionarioTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharTfActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharTfActionPerformed

    private void registroFuncionarioTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroFuncionarioTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroFuncionarioTfActionPerformed

    private void consultarTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarTfActionPerformed
        String texto = "";
        boolean arquivoExiste = true;
        String caminho = registroFuncionarioTf.getText() + "sorvete.dat";
            FileInputStream stream = null;
        try {
            stream = new FileInputStream(caminho);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Preferencia não encontrada");
            arquivoExiste = false;
        }
        if(arquivoExiste){
            InputStreamReader reader = new InputStreamReader(stream);
            BufferedReader br = new BufferedReader(reader);
            String linha = "";
            
            try {
                linha = br.readLine();
                texto = linha + "\n";
            } catch (IOException ex) {
                Logger.getLogger(ConsultaPreferencia.class.getName()).log(Level.SEVERE, null, ex);
            }
      
            while(linha != null) {

                try {
                    
                    linha = br.readLine();
                } catch (IOException ex) {
                    Logger.getLogger(ConsultaPreferencia.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(linha == null){// se a linha for nula não vai adicionala ao texto
                    break;
                }
                texto += linha; // texto sempre vai ser igual ao texto mais a linha pulando a outra linha
                texto += "\n";
          }
        inforamacoesTa.setText(texto);
            try {
                stream.close();
            } catch (IOException ex) {
                Logger.getLogger(ConsultaPreferencia.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_consultarTfActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConsultaPreferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConsultaPreferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConsultaPreferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConsultaPreferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConsultaPreferencia().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarTf;
    private javax.swing.JButton fecharTf;
    private javax.swing.JTextArea inforamacoesTa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField registroFuncionarioTf;
    // End of variables declaration//GEN-END:variables
}
